---
- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: aws-key
    instance_type: t2.micro
    security_group: default
    image: ami-09e5afc68eed60ef4
    region: eu-west-2
    subnet: subnet-082213e51ccfdcaa4 
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         user_data: "{{ lookup('file', 'user_data') }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: "{{ subnet }}"
         assign_public_ip: yes
      register: ec2
