---
- hosts: centos
  become: true
  tasks:
  - name: Install docker
    yum: name=docker state=latest
  - name: Start docker service
    service: name=docker state=started
  - name: Start flask app on port 80
    shell:
      cmd: docker run -dit -p 80:4080 ashok25/flaskapp:v2.0
